-- Migration: 20260925T0720_add_address
-- Reference copy generated by `pnpm db:sql`. Prisma applies ops.json, not this file.

-- AlterTable
ALTER TABLE "public"."user" DROP COLUMN "address";

-- CreateTable
CREATE TABLE "public"."addressSchema" (
  "address" TEXT NOT NULL,
  "city" TEXT NOT NULL,
  "country" TEXT DEFAULT 'India' NOT NULL,
  "fullName" TEXT NOT NULL,
  "id" UUID NOT NULL,
  "isDefault" BOOLEAN DEFAULT false NOT NULL,
  "postalCode" TEXT NOT NULL,
  "state" TEXT NOT NULL,
  "userId" UUID NOT NULL,
  PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "addressSchema_userId_idx_a489d58a" ON "public"."addressSchema" ("userId");

-- AlterTable
ALTER TABLE "public"."addressSchema"
ADD CONSTRAINT "addressSchema_userId_fkey"
FOREIGN KEY ("userId")
REFERENCES "public"."user" ("id")
ON DELETE CASCADE;
