-- Migration: 20260926T0708_add_banner
-- Reference copy generated by `pnpm db:sql`. Prisma applies ops.json, not this file.

-- CreateTable
CREATE TABLE "public"."banner" (
  "createdAt" TIMESTAMPTZ DEFAULT (now()) NOT NULL,
  "createdBy" UUID NOT NULL,
  "id" UUID NOT NULL,
  "imagePublicId" TEXT NOT NULL,
  "imageUrl" TEXT NOT NULL,
  "updatedAt" TIMESTAMPTZ DEFAULT (now()) NOT NULL,
  PRIMARY KEY ("id")
);

-- AlterTable
ALTER TABLE "public"."order" ALTER COLUMN "discountAmount" TYPE float8 USING "discountAmount"::float8;

-- CreateIndex
CREATE INDEX "banner_createdBy_idx_ba0f792f" ON "public"."banner" ("createdBy");

-- CreateIndex
CREATE INDEX "order_cancelled_sweep_64021f13" ON "public"."order" ("cancelledAt") WHERE (("orderStatus" = 'cancelled'));

-- AlterTable
ALTER TABLE "public"."banner"
ADD CONSTRAINT "banner_createdBy_fkey"
FOREIGN KEY ("createdBy")
REFERENCES "public"."user" ("id");
