-- Migration: 20260925T0617_add_user
-- Reference copy generated by `pnpm db:sql`. Prisma applies ops.json, not this file.

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "public"."user" (
  "address" INTEGER NOT NULL,
  "authProvider" TEXT DEFAULT 'local' NOT NULL,
  "avatar" TEXT,
  "email" TEXT NOT NULL,
  "googleId" TEXT,
  "id" UUID NOT NULL,
  "name" TEXT,
  "passwordHash" TEXT,
  "points" INTEGER DEFAULT 0 NOT NULL,
  "role" TEXT DEFAULT 'user' NOT NULL,
  "verified" BOOLEAN DEFAULT false NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_authProvider_check_7916b13c" CHECK ("authProvider" IN ('local', 'google')),
  CONSTRAINT "user_role_check_5b6d1a59" CHECK ("role" IN ('user', 'admin'))
);

-- AddConstraint
ALTER TABLE "public"."user" ADD CONSTRAINT "user_email_key" UNIQUE ("email");

-- AddConstraint
ALTER TABLE "public"."user" ADD CONSTRAINT "user_googleId_key" UNIQUE ("googleId");
