-- Migration: 20260926T0434_product_created_desc_index
-- Reference copy generated by `pnpm db:sql`. Prisma applies ops.json, not this file.

-- Statement
DROP INDEX "public"."product_status_createdAt_idx_58610442";

-- CreateIndex
CREATE INDEX "product_status_created_desc_4696f21c" ON "public"."product" (status, "createdAt" DESC);
