-- Migration: 20260925T0907_add_categories
-- Reference copy generated by `pnpm db:sql`. Prisma applies ops.json, not this file.

-- CreateTable
CREATE TABLE "public"."category" (
  "id" UUID NOT NULL,
  "name" TEXT NOT NULL,
  PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."subCategory" (
  "categoryId" UUID NOT NULL,
  "id" UUID NOT NULL,
  "name" TEXT NOT NULL,
  PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "category_name_lower_e40b0be1" ON "public"."category" (lower(name));

-- CreateIndex
CREATE INDEX "subCategory_categoryId_idx_15c304f2" ON "public"."subCategory" ("categoryId");

-- CreateIndex
CREATE UNIQUE INDEX "sub_category_name_lower_0f7f2b6e" ON "public"."subCategory" ("categoryId", lower(name));

-- AlterTable
ALTER TABLE "public"."subCategory"
ADD CONSTRAINT "subCategory_categoryId_fkey"
FOREIGN KEY ("categoryId")
REFERENCES "public"."category" ("id")
ON DELETE CASCADE;
