-- Migration: 20260926T0509_add_wishlist
-- Reference copy generated by `pnpm db:sql`. Prisma applies ops.json, not this file.

-- CreateTable
CREATE TABLE "public"."cart" (
  "createdAt" TIMESTAMPTZ DEFAULT (now()) NOT NULL,
  "id" UUID NOT NULL,
  "updatedAt" TIMESTAMPTZ DEFAULT (now()) NOT NULL,
  "userId" UUID NOT NULL,
  PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."cartItem" (
  "cartId" UUID NOT NULL,
  "color" TEXT,
  "id" UUID NOT NULL,
  "image" TEXT,
  "productId" UUID NOT NULL,
  "quantity" INTEGER NOT NULL,
  "size" TEXT,
  PRIMARY KEY ("id"),
  CONSTRAINT "cartItem_size_check_f8fc34a7" CHECK ("size" IN ('S', 'M', 'L', 'XL', 'XXL')),
  CONSTRAINT "cart_item_quantity_min_2a0d32c1" CHECK (quantity >= 1)
);

-- CreateTable
CREATE TABLE "public"."wishlist" (
  "createdAt" TIMESTAMPTZ DEFAULT (now()) NOT NULL,
  "id" UUID NOT NULL,
  "updatedAt" TIMESTAMPTZ DEFAULT (now()) NOT NULL,
  "userId" UUID NOT NULL,
  PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."wishlistProduct" (
  "createdAt" TIMESTAMPTZ DEFAULT (now()) NOT NULL,
  "productId" UUID NOT NULL,
  "wishlistId" UUID NOT NULL,
  PRIMARY KEY ("wishlistId", "productId")
);

-- AddConstraint
ALTER TABLE "public"."cart" ADD CONSTRAINT "cart_userId_key" UNIQUE ("userId");

-- AddConstraint
ALTER TABLE "public"."wishlist" ADD CONSTRAINT "wishlist_userId_key" UNIQUE ("userId");

-- CreateIndex
CREATE INDEX "cartItem_cartId_idx_79939295" ON "public"."cartItem" ("cartId");

-- CreateIndex
CREATE INDEX "cartItem_productId_idx_5858600a" ON "public"."cartItem" ("productId");

-- CreateIndex
CREATE INDEX "wishlistProduct_productId_idx_5858600a" ON "public"."wishlistProduct" ("productId");

-- CreateIndex
CREATE INDEX "wishlistProduct_wishlistId_idx_52926058" ON "public"."wishlistProduct" ("wishlistId");

-- AlterTable
ALTER TABLE "public"."cart"
ADD CONSTRAINT "cart_userId_fkey"
FOREIGN KEY ("userId")
REFERENCES "public"."user" ("id")
ON DELETE CASCADE;

-- AlterTable
ALTER TABLE "public"."cartItem"
ADD CONSTRAINT "cartItem_productId_fkey"
FOREIGN KEY ("productId")
REFERENCES "public"."product" ("id")
ON DELETE CASCADE;

-- AlterTable
ALTER TABLE "public"."cartItem"
ADD CONSTRAINT "cartItem_cartId_fkey"
FOREIGN KEY ("cartId")
REFERENCES "public"."cart" ("id")
ON DELETE CASCADE;

-- AlterTable
ALTER TABLE "public"."wishlist"
ADD CONSTRAINT "wishlist_userId_fkey"
FOREIGN KEY ("userId")
REFERENCES "public"."user" ("id")
ON DELETE CASCADE;

-- AlterTable
ALTER TABLE "public"."wishlistProduct"
ADD CONSTRAINT "wishlistProduct_wishlistId_fkey"
FOREIGN KEY ("wishlistId")
REFERENCES "public"."wishlist" ("id")
ON DELETE CASCADE;

-- AlterTable
ALTER TABLE "public"."wishlistProduct"
ADD CONSTRAINT "wishlistProduct_productId_fkey"
FOREIGN KEY ("productId")
REFERENCES "public"."product" ("id")
ON DELETE CASCADE;
