-- Migration: 20260925T0953_add_brand
-- Reference copy generated by `pnpm db:sql`. Prisma applies ops.json, not this file.

-- CreateTable
CREATE TABLE "public"."brand" (
  "id" UUID NOT NULL,
  "name" TEXT NOT NULL,
  PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "brand_name_lower_e40b0be1" ON "public"."brand" (lower(name));
