-- Migration: 20260926T0636_add_orders
-- Reference copy generated by `pnpm db:sql`. Prisma applies ops.json, not this file.

-- CreateTable
CREATE TABLE "public"."order" (
  "cancelledAt" TIMESTAMPTZ,
  "cancelledBy" TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT (now()) NOT NULL,
  "customerEmail" TEXT NOT NULL,
  "customerName" TEXT DEFAULT '' NOT NULL,
  "deliveredAt" TIMESTAMPTZ,
  "deliveryAddress" TEXT NOT NULL,
  "deliveryName" TEXT NOT NULL,
  "discountAmount" INTEGER DEFAULT 0 NOT NULL,
  "id" UUID NOT NULL,
  "orderStatus" TEXT DEFAULT 'pending_payment' NOT NULL,
  "paidAt" TIMESTAMPTZ,
  "paymentId" TEXT DEFAULT '' NOT NULL,
  "paymentStatus" TEXT DEFAULT 'pending' NOT NULL,
  "promoCode" TEXT DEFAULT '' NOT NULL,
  "razorpayOrderId" TEXT NOT NULL,
  "returnedAt" TIMESTAMPTZ,
  "shippedAt" TIMESTAMPTZ,
  "totalAmount" DOUBLE PRECISION NOT NULL,
  "totalItems" INTEGER NOT NULL,
  "updatedAt" TIMESTAMPTZ DEFAULT (now()) NOT NULL,
  "userId" UUID NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "order_cancelledBy_check_2cc69f64" CHECK ("cancelledBy" IN ('customer', 'admin')),
  CONSTRAINT "order_discount_amount_min_f2689c28" CHECK ("discountAmount" >= 0),
  CONSTRAINT "order_orderStatus_check_a252a221" CHECK ("orderStatus" IN ('pending_payment', 'placed', 'shipped', 'delivered', 'returned', 'cancelled')),
  CONSTRAINT "order_paymentStatus_check_ad13dc0d" CHECK ("paymentStatus" IN ('pending', 'paid', 'failed')),
  CONSTRAINT "order_promo_code_uppercase_fafa66df" CHECK ("promoCode" = upper(btrim("promoCode"))),
  CONSTRAINT "order_total_amount_min_a0230a06" CHECK ("totalAmount" >= 0),
  CONSTRAINT "order_total_item_min_f8d723e1" CHECK ("totalItems" >= 1)
);

-- CreateTable
CREATE TABLE "public"."orderItem" (
  "color" TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT (now()) NOT NULL,
  "id" UUID NOT NULL,
  "itemTotal" DOUBLE PRECISION NOT NULL,
  "orderId" UUID NOT NULL,
  "productId" UUID NOT NULL,
  "quantity" INTEGER NOT NULL,
  "size" TEXT,
  "unitPrice" DOUBLE PRECISION NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "orderItem_size_check_f8fc34a7" CHECK ("size" IN ('S', 'M', 'L', 'XL', 'XXL')),
  CONSTRAINT "order_item_quantity_min_2a0d32c1" CHECK (quantity >= 1),
  CONSTRAINT "order_item_total_min_f42006c1" CHECK ("itemTotal" >= 0),
  CONSTRAINT "order_item_unit_price_min_07e3086a" CHECK ("unitPrice" >= 0)
);

-- AddConstraint
ALTER TABLE "public"."order" ADD CONSTRAINT "order_razorpayOrderId_key" UNIQUE ("razorpayOrderId");

-- AddConstraint
ALTER TABLE "public"."promo" ADD CONSTRAINT "promo_code_uppercase_trimmed_099b454a" CHECK (code = upper(btrim(code)));

-- CreateIndex
CREATE INDEX "order_orderStatus_createdAt_ffff26ab" ON "public"."order" ("orderStatus", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "order_paymentStatus_createdAt_8dac5b5c" ON "public"."order" ("paymentStatus", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "order_userId_createdAt_0ea562f9" ON "public"."order" ("userId", "createdAt" DESC);

-- CreateIndex
CREATE INDEX "order_userId_idx_a489d58a" ON "public"."order" ("userId");

-- CreateIndex
CREATE INDEX "orderItem_orderId_idx_d284871b" ON "public"."orderItem" ("orderId");

-- CreateIndex
CREATE INDEX "orderItem_productId_idx_5858600a" ON "public"."orderItem" ("productId");

-- AlterTable
ALTER TABLE "public"."order"
ADD CONSTRAINT "order_userId_fkey"
FOREIGN KEY ("userId")
REFERENCES "public"."user" ("id");

-- AlterTable
ALTER TABLE "public"."orderItem"
ADD CONSTRAINT "orderItem_orderId_fkey"
FOREIGN KEY ("orderId")
REFERENCES "public"."order" ("id")
ON DELETE CASCADE;

-- AlterTable
ALTER TABLE "public"."orderItem"
ADD CONSTRAINT "orderItem_productId_fkey"
FOREIGN KEY ("productId")
REFERENCES "public"."product" ("id");
