-- Migration: 20260925T0855_add_verification_link
-- Reference copy generated by `pnpm db:sql`. Prisma applies ops.json, not this file.

-- CreateTable
CREATE TABLE "public"."verificationLink" (
  "createdAt" TIMESTAMPTZ DEFAULT (now()) NOT NULL,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "id" UUID NOT NULL,
  "token" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "verificationLink_expiresAt_idx_6b6b8c10" ON "public"."verificationLink" ("expiresAt");

-- CreateIndex
CREATE INDEX "verificationLink_token_idx_8b25281e" ON "public"."verificationLink" ("token");
