import { execFileSync } from "node:child_process";
import { readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

// Prisma 8 applies a migration from ops.json and never writes a .sql file. This script asks the CLI
// for each migration's SQL statements and saves them as a readable migration.sql beside it.
// It is a reference copy for review, not something `prisma db migrate` reads.

const MIGRATIONS_DIR = join("migrations", "app");

// Postgres' internal type names -> the names people write by hand.
const TYPE_NAMES: Record<string, string> = {
  int2: "SMALLINT",
  int4: "INTEGER",
  int8: "BIGINT",
  float4: "REAL",
  float8: "DOUBLE PRECISION",
  bool: "BOOLEAN",
  text: "TEXT",
  uuid: "UUID",
  jsonb: "JSONB",
  timestamptz: "TIMESTAMPTZ",
  timestamp: "TIMESTAMP",
};

type Statement = { text: string };

const heading = (sql: string) => {
  if (/^CREATE SCHEMA/i.test(sql)) return "CreateSchema";
  if (/^CREATE TABLE/i.test(sql)) return "CreateTable";
  if (/^CREATE (UNIQUE )?INDEX/i.test(sql)) return "CreateIndex";
  if (/^ALTER TABLE .* ADD CONSTRAINT .* FOREIGN KEY/is.test(sql)) return "AddForeignKey";
  if (/^ALTER TABLE .* ADD CONSTRAINT/is.test(sql)) return "AddConstraint";
  if (/^ALTER TABLE/i.test(sql)) return "AlterTable";
  if (/^DROP TABLE/i.test(sql)) return "DropTable";
  return "Statement";
};

// Only column lines inside CREATE TABLE look like `  "name" int4 ...`, so constraints are left alone.
const prettyTypes = (sql: string) =>
  sql.replace(/^(\s+"[^"]+"\s+)([a-z0-9]+)/gm, (line, head: string, type: string) =>
    TYPE_NAMES[type] ? head + TYPE_NAMES[type] : line,
  );

const statementsFor = (name: string): Statement[] => {
  const stdout = execFileSync("pnpm", ["exec", "prisma", "migration", "show", name, "--json"], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  });
  const lines = stdout.split("\n").filter((line) => line.startsWith("{"));
  const result = lines
    .map((line) => JSON.parse(line))
    .find((entry) => entry.kind === "result")?.envelope?.result;
  const statements = result?.preview?.statements ?? result?.migration?.preview?.statements;
  if (!Array.isArray(statements)) {
    throw new Error(`No SQL preview in \`prisma migration show ${name}\` output`);
  }
  return statements;
};

const only = process.argv[2];
const names = readdirSync(MIGRATIONS_DIR, { withFileTypes: true })
  .filter((entry) => entry.isDirectory() && entry.name !== "refs")
  .map((entry) => entry.name)
  .filter((name) => !only || name === only);

if (names.length === 0) {
  console.error(only ? `No migration named ${only}` : "No migrations found. Run `pnpm db:plan <name>` first.");
  process.exit(1);
}

for (const name of names) {
  const blocks = statementsFor(name).map(({ text }) => `-- ${heading(text)}\n${prettyTypes(text)};`);
  const header = `-- Migration: ${name}\n-- Reference copy generated by \`pnpm db:sql\`. Prisma applies ops.json, not this file.\n`;
  writeFileSync(join(MIGRATIONS_DIR, name, "migration.sql"), `${header}\n${blocks.join("\n\n")}\n`);
  console.log(`wrote ${join(MIGRATIONS_DIR, name, "migration.sql")}`);
}
