-- Migration: 20261003T0900_add_product_image_position
-- Reference copy generated by `pnpm db:sql`. Prisma applies ops.json, not this file.

-- Statement
DROP INDEX "public"."productImage_productId_idx_5858600a";

-- AlterTable
ALTER TABLE "public"."productImage" ADD COLUMN "position" int4 DEFAULT 0 NOT NULL;

-- CreateIndex
CREATE INDEX "productImage_productId_position_idx_902b1475" ON "public"."productImage" ("productId", "position");
