-- Migration: 20260925T1705_add_products_and_timestamps
-- Reference copy generated by `pnpm db:sql`. Prisma applies ops.json, not this file.

-- DropTable
DROP TABLE "public"."addressSchema";

-- CreateTable
CREATE TABLE "public"."address" (
  "address" TEXT NOT NULL,
  "city" TEXT NOT NULL,
  "country" TEXT DEFAULT 'India' NOT NULL,
  "fullName" TEXT NOT NULL,
  "id" UUID NOT NULL,
  "isDefault" BOOLEAN DEFAULT false NOT NULL,
  "postalCode" TEXT NOT NULL,
  "state" TEXT NOT NULL,
  "userId" UUID NOT NULL,
  PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."product" (
  "brandId" UUID NOT NULL,
  "categoryId" UUID NOT NULL,
  "colors" TEXT[] NOT NULL,
  "createdAt" TIMESTAMPTZ DEFAULT (now()) NOT NULL,
  "createdBy" UUID NOT NULL,
  "description" TEXT NOT NULL,
  "id" UUID NOT NULL,
  "price" DOUBLE PRECISION NOT NULL,
  "salesPercentage" DOUBLE PRECISION DEFAULT 0 NOT NULL,
  "sizes" TEXT[] NOT NULL,
  "status" TEXT DEFAULT 'active' NOT NULL,
  "subCategoryId" UUID,
  "title" TEXT NOT NULL,
  "updatedAt" TIMESTAMPTZ DEFAULT (now()) NOT NULL,
  "uploadError" TEXT,
  "uploadStatus" TEXT DEFAULT 'PENDING' NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "product_colors_elem_not_null_7d4593f4" CHECK (array_position("colors", NULL) IS NULL),
  CONSTRAINT "product_sizes_check_3ad39f47" CHECK ("sizes"::text[] <@ ARRAY['S', 'M', 'L', 'XL', 'XXL']::text[]),
  CONSTRAINT "product_sizes_elem_not_null_099c54be" CHECK (array_position("sizes", NULL) IS NULL),
  CONSTRAINT "product_status_check_11063666" CHECK ("status" IN ('active', 'inactive')),
  CONSTRAINT "product_uploadStatus_check_8a00e20d" CHECK ("uploadStatus" IN ('PENDING', 'PROCESSING', 'READY', 'FAILED'))
);

-- CreateTable
CREATE TABLE "public"."productImage" (
  "color" TEXT,
  "id" UUID NOT NULL,
  "isCover" BOOLEAN DEFAULT false NOT NULL,
  "productId" UUID NOT NULL,
  "publicId" TEXT NOT NULL,
  "url" TEXT NOT NULL,
  PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."productVariant" (
  "color" TEXT,
  "id" UUID NOT NULL,
  "productId" UUID NOT NULL,
  "size" TEXT,
  "stock" INTEGER DEFAULT 0 NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "productVariant_size_check_f8fc34a7" CHECK ("size" IN ('S', 'M', 'L', 'XL', 'XXL')),
  CONSTRAINT "product_variant_stock_nonneg_fd296d5d" CHECK (stock >= 0)
);

-- AlterTable
ALTER TABLE "public"."brand" ADD COLUMN "createdAt" timestamptz DEFAULT (now()) NOT NULL;

-- AlterTable
ALTER TABLE "public"."brand" ADD COLUMN "updatedAt" timestamptz DEFAULT (now()) NOT NULL;

-- AlterTable
ALTER TABLE "public"."category" ADD COLUMN "createdAt" timestamptz DEFAULT (now()) NOT NULL;

-- AlterTable
ALTER TABLE "public"."category" ADD COLUMN "updatedAt" timestamptz DEFAULT (now()) NOT NULL;

-- AlterTable
ALTER TABLE "public"."subCategory" ADD COLUMN "createdAt" timestamptz DEFAULT (now()) NOT NULL;

-- AlterTable
ALTER TABLE "public"."subCategory" ADD COLUMN "updatedAt" timestamptz DEFAULT (now()) NOT NULL;

-- AlterTable
ALTER TABLE "public"."user" ADD COLUMN "createdAt" timestamptz DEFAULT (now()) NOT NULL;

-- AlterTable
ALTER TABLE "public"."user" ADD COLUMN "updatedAt" timestamptz DEFAULT (now()) NOT NULL;

-- AlterTable
ALTER TABLE "public"."verificationLink" ADD COLUMN "userId" uuid;

-- AlterTable
ALTER TABLE "public"."verificationLink" ALTER COLUMN "userId" SET NOT NULL;

-- AlterTable
ALTER TABLE "public"."session" ALTER COLUMN "userAgent" DROP NOT NULL;

-- CreateIndex
CREATE INDEX "address_userId_idx_a489d58a" ON "public"."address" ("userId");

-- CreateIndex
CREATE INDEX "product_brandId_idx_02e95397" ON "public"."product" ("brandId");

-- CreateIndex
CREATE INDEX "product_brandId_status_idx_aa7448c7" ON "public"."product" ("brandId", "status");

-- CreateIndex
CREATE INDEX "product_categoryId_idx_15c304f2" ON "public"."product" ("categoryId");

-- CreateIndex
CREATE INDEX "product_categoryId_status_idx_89e9b532" ON "public"."product" ("categoryId", "status");

-- CreateIndex
CREATE INDEX "product_createdBy_idx_ba0f792f" ON "public"."product" ("createdBy");

-- CreateIndex
CREATE INDEX "product_status_createdAt_idx_58610442" ON "public"."product" ("status", "createdAt");

-- CreateIndex
CREATE INDEX "product_status_price_idx_d94abea6" ON "public"."product" ("status", "price");

-- CreateIndex
CREATE INDEX "product_subCategoryId_idx_71e8c282" ON "public"."product" ("subCategoryId");

-- CreateIndex
CREATE INDEX "product_subCategoryId_status_idx_eb1f41c5" ON "public"."product" ("subCategoryId", "status");

-- CreateIndex
CREATE INDEX "productImage_productId_idx_5858600a" ON "public"."productImage" ("productId");

-- CreateIndex
CREATE INDEX "productVariant_productId_idx_5858600a" ON "public"."productVariant" ("productId");

-- CreateIndex
CREATE INDEX "verificationLink_userId_idx_a489d58a" ON "public"."verificationLink" ("userId");

-- AlterTable
ALTER TABLE "public"."address"
ADD CONSTRAINT "address_userId_fkey"
FOREIGN KEY ("userId")
REFERENCES "public"."user" ("id")
ON DELETE CASCADE;

-- AlterTable
ALTER TABLE "public"."product"
ADD CONSTRAINT "product_categoryId_fkey"
FOREIGN KEY ("categoryId")
REFERENCES "public"."category" ("id");

-- AlterTable
ALTER TABLE "public"."product"
ADD CONSTRAINT "product_brandId_fkey"
FOREIGN KEY ("brandId")
REFERENCES "public"."brand" ("id");

-- AlterTable
ALTER TABLE "public"."product"
ADD CONSTRAINT "product_subCategoryId_fkey"
FOREIGN KEY ("subCategoryId")
REFERENCES "public"."subCategory" ("id");

-- AlterTable
ALTER TABLE "public"."product"
ADD CONSTRAINT "product_createdBy_fkey"
FOREIGN KEY ("createdBy")
REFERENCES "public"."user" ("id");

-- AlterTable
ALTER TABLE "public"."productImage"
ADD CONSTRAINT "productImage_productId_fkey"
FOREIGN KEY ("productId")
REFERENCES "public"."product" ("id")
ON DELETE CASCADE;

-- AlterTable
ALTER TABLE "public"."productVariant"
ADD CONSTRAINT "productVariant_productId_fkey"
FOREIGN KEY ("productId")
REFERENCES "public"."product" ("id")
ON DELETE CASCADE;

-- AlterTable
ALTER TABLE "public"."verificationLink"
ADD CONSTRAINT "verificationLink_userId_fkey"
FOREIGN KEY ("userId")
REFERENCES "public"."user" ("id")
ON DELETE CASCADE;
