-- Migration: 20260926T0530_add_promo
-- Reference copy generated by `pnpm db:sql`. Prisma applies ops.json, not this file.

-- CreateTable
CREATE TABLE "public"."promo" (
  "code" TEXT NOT NULL,
  "count" INTEGER DEFAULT 0 NOT NULL,
  "createdAt" TIMESTAMPTZ DEFAULT (now()) NOT NULL,
  "endsAt" TIMESTAMPTZ NOT NULL,
  "id" UUID NOT NULL,
  "minimumOrderValue" DOUBLE PRECISION DEFAULT 0 NOT NULL,
  "percentage" DOUBLE PRECISION NOT NULL,
  "startsAt" TIMESTAMPTZ NOT NULL,
  "updatedAt" TIMESTAMPTZ DEFAULT (now()) NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "promo_count_min_857bca31" CHECK (count >= 0),
  CONSTRAINT "promo_minimum_order_value_847d9933" CHECK ("minimumOrderValue" >= 0),
  CONSTRAINT "promo_percentage_range_5e052d98" CHECK (percentage >= 1 AND percentage <= 100)
);

-- AddConstraint
ALTER TABLE "public"."promo" ADD CONSTRAINT "promo_code_key" UNIQUE ("code");
