-- Migration: 20260926T0943_schema_fixes
-- Reference copy generated by `pnpm db:sql`. Prisma applies ops.json, not this file.

-- DropTable
DROP TABLE "public"."orderItem";

-- Statement
DROP INDEX "public"."verificationLink_token_idx_8b25281e";

-- AlterTable
ALTER TABLE "public"."order" ALTER COLUMN "discountAmount" TYPE int4 USING "discountAmount"::int4;

-- AlterTable
ALTER TABLE "public"."order" ALTER COLUMN "totalAmount" TYPE int4 USING "totalAmount"::int4;

-- AlterTable
ALTER TABLE "public"."product" ALTER COLUMN "price" TYPE int4 USING "price"::int4;

-- AlterTable
ALTER TABLE "public"."promo" ALTER COLUMN "minimumOrderValue" TYPE int4 USING "minimumOrderValue"::int4;

-- AddConstraint
ALTER TABLE "public"."verificationLink" ADD CONSTRAINT "verificationLink_type_check_c88c716f" CHECK ("type" IN ('email_verification', 'password_reset'));

-- AddConstraint
ALTER TABLE "public"."verificationLink" ADD CONSTRAINT "verificationLink_token_key" UNIQUE ("token");

-- CreateIndex
CREATE INDEX "product_colors_gin_708d437b" ON "public"."product" USING "gin" ("colors");

-- CreateIndex
CREATE INDEX "product_sizes_gin_f1a51111" ON "public"."product" USING "gin" ("sizes");

-- CreateIndex
CREATE UNIQUE INDEX "product_variant_unique_04a28d33" ON "public"."productVariant" ("productId", coalesce(color, ''), coalesce(size, ''));
