-- Migration: 20260925T0821_add_session
-- Reference copy generated by `pnpm db:sql`. Prisma applies ops.json, not this file.

-- CreateTable
CREATE TABLE "public"."session" (
  "createdAt" TIMESTAMPTZ DEFAULT (now()) NOT NULL,
  "expiresAt" TIMESTAMPTZ DEFAULT ((CURRENT_TIMESTAMP + '30 days'::interval)) NOT NULL,
  "id" UUID NOT NULL,
  "prevRefreshJti" TEXT,
  "refreshJti" TEXT NOT NULL,
  "rotatedAt" TIMESTAMPTZ,
  "userAgent" TEXT NOT NULL,
  "userId" UUID NOT NULL,
  PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "session_expiresAt_idx_6b6b8c10" ON "public"."session" ("expiresAt");

-- CreateIndex
CREATE INDEX "session_userId_idx_a489d58a" ON "public"."session" ("userId");

-- AlterTable
ALTER TABLE "public"."session"
ADD CONSTRAINT "session_userId_fkey"
FOREIGN KEY ("userId")
REFERENCES "public"."user" ("id")
ON DELETE CASCADE;
