-- Migration: 20260926T0944_recreate_order_item
-- Reference copy generated by `pnpm db:sql`. Prisma applies ops.json, not this file.

-- CreateTable
CREATE TABLE "public"."orderItem" (
  "color" TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT (now()) NOT NULL,
  "id" UUID NOT NULL,
  "itemTotal" INTEGER NOT NULL,
  "orderId" UUID NOT NULL,
  "productId" UUID,
  "quantity" INTEGER NOT NULL,
  "size" TEXT,
  "unitPrice" INTEGER NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "orderItem_size_check_f8fc34a7" CHECK ("size" IN ('S', 'M', 'L', 'XL', 'XXL')),
  CONSTRAINT "order_item_quantity_min_2a0d32c1" CHECK (quantity >= 1),
  CONSTRAINT "order_item_total_min_f42006c1" CHECK ("itemTotal" >= 0),
  CONSTRAINT "order_item_unit_price_min_07e3086a" CHECK ("unitPrice" >= 0)
);

-- CreateIndex
CREATE INDEX "orderItem_orderId_idx_d284871b" ON "public"."orderItem" ("orderId");

-- CreateIndex
CREATE INDEX "orderItem_productId_idx_5858600a" ON "public"."orderItem" ("productId");

-- AlterTable
ALTER TABLE "public"."orderItem"
ADD CONSTRAINT "orderItem_orderId_fkey"
FOREIGN KEY ("orderId")
REFERENCES "public"."order" ("id")
ON DELETE CASCADE;

-- AlterTable
ALTER TABLE "public"."orderItem"
ADD CONSTRAINT "orderItem_productId_fkey"
FOREIGN KEY ("productId")
REFERENCES "public"."product" ("id")
ON DELETE SET NULL;
