-- Migration: 20260929T1634_phase01_fixes
-- Reference copy generated by `pnpm db:sql`. Prisma applies ops.json, not this file.

-- AlterTable
ALTER TABLE "public"."orderItem" ADD COLUMN "image" text;

-- AlterTable
ALTER TABLE "public"."orderItem" ADD COLUMN "title" text DEFAULT '' NOT NULL;

-- AlterTable
ALTER TABLE "public"."product" ALTER COLUMN "salesPercentage" TYPE int4 USING "salesPercentage"::int4;

-- AlterTable
ALTER TABLE "public"."promo" ALTER COLUMN "percentage" TYPE int4 USING "percentage"::int4;

-- CreateIndex
CREATE UNIQUE INDEX "address_one_default_8a30964e" ON "public"."address" ("userId") WHERE ("isDefault");

-- CreateIndex
CREATE UNIQUE INDEX "cart_item_unique_312d3cd5" ON "public"."cartItem" ("cartId", "productId", coalesce(color, ''), coalesce(size, ''));

-- Statement
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- CreateIndex
CREATE INDEX "product_title_trgm_dbf5ca54" ON "public"."product" USING "gin" (title gin_trgm_ops);

-- CreateIndex
CREATE UNIQUE INDEX "product_image_one_cover_f9da048c" ON "public"."productImage" ("productId") WHERE ("isCover");

-- Statement
CREATE OR REPLACE FUNCTION "public"."set_updated_at"() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$;

-- Statement
CREATE OR REPLACE TRIGGER "user_set_updated_at" BEFORE UPDATE ON "public"."user" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

-- Statement
CREATE OR REPLACE TRIGGER "category_set_updated_at" BEFORE UPDATE ON "public"."category" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

-- Statement
CREATE OR REPLACE TRIGGER "subCategory_set_updated_at" BEFORE UPDATE ON "public"."subCategory" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

-- Statement
CREATE OR REPLACE TRIGGER "brand_set_updated_at" BEFORE UPDATE ON "public"."brand" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

-- Statement
CREATE OR REPLACE TRIGGER "product_set_updated_at" BEFORE UPDATE ON "public"."product" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

-- Statement
CREATE OR REPLACE TRIGGER "cart_set_updated_at" BEFORE UPDATE ON "public"."cart" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

-- Statement
CREATE OR REPLACE TRIGGER "wishlist_set_updated_at" BEFORE UPDATE ON "public"."wishlist" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

-- Statement
CREATE OR REPLACE TRIGGER "promo_set_updated_at" BEFORE UPDATE ON "public"."promo" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

-- Statement
CREATE OR REPLACE TRIGGER "order_set_updated_at" BEFORE UPDATE ON "public"."order" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();

-- Statement
CREATE OR REPLACE TRIGGER "banner_set_updated_at" BEFORE UPDATE ON "public"."banner" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();
